version: "3.0"
services:
  csvserver:
    image: infracloudio/csvserver
    container_name: csvserver
    ports:
      - "9393:9300"
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
      - ./inputFile:/csvserver/inputdata
    command: "/csvserver/csvserver"

  monit:
    image: prom/prometheus
    container_name: monitor
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
